name: google_places_flutter
description: Custom Google places autocomplete widget for Android and iOS both. Use https://pub.dev/packages/google_places_flutter
version: 2.1.0
homepage: https://github.com/Shrutimahajan/Google-AutoComplete-TextField-Flutter

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  rxdart: ^0.28.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
     - images/location.json